name: turbo-repost-bot deploy

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.repository }}-${{ github.ref_name }}
  cancel-in-progress: true

env:
  REPO_NAME: turbo_repost_bot

jobs:
  analyze:
    name: Analyze existing container
    runs-on: [self-hosted, windows]
    outputs:
      was-running: ${{ steps.check.outputs.running }}
    steps:
      - name: Check if container is running
        id: check
        shell: powershell
        run: |
          $name    = "${{ env.REPO_NAME }}"
          $running = if (docker ps -q -f name=$name) { 'true' } else { 'false' }
          echo "running=$running" >> $env:GITHUB_OUTPUT
          if ($running -eq 'true') {
            Write-Host "Container '$name' was running before update."
          } else {
            Write-Host "Container '$name' was NOT running."
          }

  teardown:
    name: Teardown old container
    runs-on: [self-hosted, windows]
    needs: analyze
    if: always()
    steps:
      - name: Stop & remove container
        shell: powershell
        run: |
          $name = "${{ env.REPO_NAME }}"
          if (docker ps -a -q -f name=$name) {
            Write-Host "Stopping and removing container '$name'..."
            docker rm -f $name
          } else {
            Write-Host "No container '$name' to remove."
          }

  delete-image:
    name: Delete old images
    runs-on: [self-hosted, windows]
    steps:
      - name: Remove all images named $REPO_NAME
        shell: powershell
        run: |
          $name = "${{ env.REPO_NAME }}"
          $ids  = docker images -q $name
          if ($ids) {
            Write-Host "Removing images: $ids"
            $ids | ForEach-Object { docker rmi -f $_ }
          } else {
            Write-Host "No images named '$name' found."
          }

  build-image:
    name: Build new Docker image
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Build image
        shell: powershell
        run: |
          $repo = "${{ env.REPO_NAME }}"
          Write-Host "Building image '${repo}:latest'..."
          docker build -t "${repo}:latest" .

  run-container:
    name: Run new container
    runs-on: [self-hosted, windows]
    needs:
      - teardown
      - build-image
    steps:
      - name: Start container
        shell: powershell
        run: |
          $repo = "${{ env.REPO_NAME }}"
          Write-Host "Starting container '$repo' from image '$repo:latest'..."
          docker run -d --name $repo -e BOT_TOKEN="${{ secrets.BOT_TOKEN }}" "$repo:latest"

  verify:
    name: Verify container health
    runs-on: [self-hosted, windows]
    needs: run-container
    steps:
      - name: Wait 5s and check running state
        shell: powershell
        run: |
          $name  = "${{ env.REPO_NAME }}"
          Start-Sleep -Seconds 5
          $state = (docker inspect -f '{{.State.Status}}' $name).Trim()
          if ($state -eq 'running') {
            Write-Host "Container '$name' is running."
          } else {
            Write-Error "Container '$name' state is '$state'. Failing."
            exit 1
          }
